<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Ping project</title>
    <link rel="stylesheet" href="assets/bootstrap/css/bootstrap.min.css">
    <link rel="stylesheet" href="assets/fonts/font-awesome.min.css">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Alegreya+Sans+SC">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Anton">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Archivo+Narrow">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Cookie">
    <link rel="stylesheet" href="assets/css/-Login-form-Page-BS4-.css">
    <link rel="stylesheet" href="assets/css/Article-Cards.css">
    <link rel="stylesheet" href="assets/css/Bold-BS4-Cards-with-Hover-Effect-115.css">
    <link rel="stylesheet" href="assets/css/Bold-BS4-Cards-with-Hover-Effect-115.css">
    <link rel="stylesheet" href="assets/css/Bold-BS4-Cards-with-Hover-Effect-50.css">
    <link rel="stylesheet" href="assets/css/Bold-BS4-Cards-with-Hover-Effect-50.css">
    <link rel="stylesheet" href="assets/css/Card-Group-Classic.css">
    <link rel="stylesheet" href="assets/css/Carousel-Hero.css">
    <link rel="stylesheet" href="assets/css/Footer-Clean.css">
    <link rel="stylesheet" href="assets/css/Google-Style-Login.css">
    <link rel="stylesheet" href="assets/css/Pretty-Footer.css">
    <link rel="stylesheet" href="assets/css/Highlight-Clean.css">
    <link rel="stylesheet" href="assets/css/News-Cards.css">
    <link rel="stylesheet" href="assets/css/Popup-Element-Overlay.css">
    <link rel="stylesheet" href="assets/css/Popup-Element-Overlay.css">
    <link rel="stylesheet" href="assets/css/styles.css">
</head>

<body>
    <nav class="navbar navbar-light navbar-expand sticky-top bg-white">
        <div class="container-fluid">
            <a class="navbar-brand text-success" href="#">Booster by CA</a>
            <button class="navbar-toggler" data-toggle="collapse" data-target="#navcol-1">
                <span class="sr-only">Toggle navigation</span><span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse mr-auto"id="navcol-1">
                <ul class="nav navbar-nav"></ul>
                <a class="btn btn-primary ml-auto" role="button" href="#myModal" data-toggle="modal" style="padding:6px 12px;margin-bottom:0px;background-color:#006a4e;">Se connecter</a>
            </div>
        </div>
    </nav>
    
    <div>
        <div class="modal fade" role="dialog" tabindex="-1" id="myModal">
            <div class="modal-dialog" role="document">
                <div class="modal-content">
                    <div class="modal-body">
                        <div class="login-card" style="margin-top:25px;"><img src="assets/img/avatar_2x.png" class="profile-img-card">
                            <p class="profile-name-card"> </p>
                            <form method="post" action="../controllers/connexion.php" class="form-group">
                                <?php
                                    session_start();
                                    if (isset($_SESSION['error_connexion'])) {
                                        foreach ($_SESSION['error_connexion'] as $erreur) {
                                            echo  '<p style="color: red">'.$erreur . '</p>';
                                        }
                                    }
                                    //var_dump($_SESSION);
                                ?>

                                <div class="form-group col-xs-12 col-sm-12 col-md-12 col-lg-12">
                                    <label for="id">Identifiant :</label>
                                    <input type="text" class="form-control" id="id" name="id" required/>
                                </div>

                                <div class="form-group col-xs-12 col-sm-12 col-md-12 col-lg-12">
                                    <label for="password">Mot de passe :</label>
                                    <input type="password" class="form-control" id="password" name="password" required/>
                                </div>
                                <div class="form-group col-xs-12 col-sm-12 col-md-12 col-lg-12">
                                    <button class="btn btn-primary btn-block btn-lg btn-signin" name="connexion" type="submit" style="margin-left:0px;">Se connecter</button>
                                </div>
                            </form>
                                <a href="#" class="forgot-password">Vous avez oublié vos identifiants ?</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="carousel slide" data-ride="carousel" id="carousel-1" style="margin-top:50px;">
        <div class="carousel-inner" role="listbox">
            <div class="carousel-item active">
                <div class="jumbotron hero-nature carousel-hero" style="background-image:url(&quot;assets/img/Shops.jpeg&quot;);background-size:cover;">
                    <h1 class="hero-title" style="color:#ffffff;">Un outil pour votre commerce</h1>
                    <p class="hero-subtitle" style="background-color:#33383b;">Reporting d'activité, chiffres clés</p>
                    <p><a class="btn btn-primary btn-lg hero-button" role="button" href="#" style="background-color:#006a4e;">En savoir plus</a></p>
                </div>
            </div>
            <div class="carousel-item">
                <div class="jumbotron hero-photography carousel-hero" style="background-image:url(&quot;assets/img/facebook-boulanger-1024x683.jpg&quot;);">
                    <h1 class="hero-title">Destiné aux petits commercants</h1>
                    <p class="hero-subtitle" style="background-color:#33383b;">Un outil de business intelligence, ouvert pour tous les clients CA</p>
                    <p><a class="btn btn-primary btn-lg hero-button" role="button" href="#" style="background-color:#006a4e;">En savoir plus</a></p>
                </div>
            </div>
            <div class="carousel-item">
                <div class="jumbotron hero-technology carousel-hero" style="background-image:url(&quot;assets/img/recruitment-consultants-more-clients.jpg&quot;);">
                    <h1 class="hero-title">Des conseillers à votre écoute</h1>
                    <p class="hero-subtitle" style="color:#ffffff;background-color:#33383b;">Votre conseiller disponible pour piloter votre commerce</p>
                    <p><a class="btn btn-primary btn-lg hero-button" role="button" href="#" style="background-color:#006a4e;">Learn more</a></p>
                </div>
            </div>
        </div>
        <div><a class="carousel-control-prev" href="#carousel-1" role="button" data-slide="prev"><i class="fa fa-chevron-left"></i><span class="sr-only">Previous</span></a><a class="carousel-control-next" href="#carousel-1" role="button" data-slide="next"><i class="fa fa-chevron-right"></i><span class="sr-only">Next</span></a></div>
        <ol
            class="carousel-indicators">
            <li data-target="#carousel-1" data-slide-to="0" class="active"></li>
            <li data-target="#carousel-1" data-slide-to="1"></li>
            <li data-target="#carousel-1" data-slide-to="2"></li>
            </ol>
    </div>
    <div class="footer-clean" style="padding-top:0px;">
        <footer>
            <div class="row">
                <div class="col-sm-6 col-md-4 footer-navigation">
                    <h3></h3>
                    <h2 style="color:#006a4e;padding-bottom:30px;">Credit Agricole</h2>
                    <p class="links"><a href="#">Acceuil</a><strong> · </strong><a href="#">Blog</a><strong>&nbsp;· </strong><a href="#">A Propos</a><strong> · </strong><a href="#">FAQ</a><strong> · </strong><a href="#">Contact</a></p>
                    <p class="company-name">Crédit Agricole Normandie © 2018</p>
                </div>
                <div class="col-sm-6 col-md-4 footer-contacts">
                    <div><span class="fa fa-map-marker footer-contacts-icon"> </span>
                        <p><span class="new-line-span">15 esplanade Brillaud de Laujardière<br></span> Caen, France</p>
                    </div>
                    <div><i class="fa fa-phone footer-contacts-icon"></i>
                        <p class="footer-center-info email text-left"><a href="tel:+33231552424">02 31 55 24 24</a><br></p>
                    </div>
                    <div><i class="fa fa-envelope footer-contacts-icon"></i>
                        <p> <a href="#" target="_blank">support@creditagricole.com</a></p>
                    </div>
                </div>
                <div class="clearfix"></div>
                <div class="col-md-4 footer-about">
                    <h4>A propos de l'entreprise</h4>
                    <p> Lorem ipsum dolor sit amet, consectateur adispicing elit. Fusce euismod convallis velit, eu auctor lacus vehicula sit amet. </p>
                    <div class="social-links social-icons"><a href="#"><i class="fa fa-facebook"></i></a><a href="#"><i class="fa fa-twitter"></i></a><a href="#"><i class="fa fa-linkedin"></i></a><a href="#"><i class="fa fa-github"></i></a></div>
                </div>
            </div>
        </footer>
    </div>
    <script src="assets/js/jquery.min.js"></script>
    <script src="assets/bootstrap/js/bootstrap.min.js"></script>
    <script src="assets/js/Popup-Element-Overlay.js"></script>
    <script src="assets/js/Subscribe-Popup-Window.js"></script>
</body>

</html>