<?php
require ('../controllers/verif_authentification.php');
?>
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Ping project</title>
    <link rel="stylesheet" href="assets/bootstrap/css/bootstrap.min.css">
    <link rel="stylesheet" href="assets/fonts/font-awesome.min.css">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Alegreya+Sans+SC">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Anton">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Archivo+Narrow">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Cookie">
    <link rel="stylesheet" href="assets/css/-Login-form-Page-BS4-.css">
    <link rel="stylesheet" href="assets/css/Article-Cards.css">
    <link rel="stylesheet" href="assets/css/Bold-BS4-Cards-with-Hover-Effect-115.css">
    <link rel="stylesheet" href="assets/css/Bold-BS4-Cards-with-Hover-Effect-115.css">
    <link rel="stylesheet" href="assets/css/Bold-BS4-Cards-with-Hover-Effect-50.css">
    <link rel="stylesheet" href="assets/css/Bold-BS4-Cards-with-Hover-Effect-50.css">
    <link rel="stylesheet" href="assets/css/Card-Group-Classic.css">
    <link rel="stylesheet" href="assets/css/Carousel-Hero.css">
    <link rel="stylesheet" href="assets/css/Footer-Clean.css">
    <link rel="stylesheet" href="assets/css/Google-Style-Login.css">
    <link rel="stylesheet" href="assets/css/Pretty-Footer.css">
    <link rel="stylesheet" href="assets/css/Highlight-Clean.css">
    <link rel="stylesheet" href="assets/css/News-Cards.css">
    <link rel="stylesheet" href="assets/css/Popup-Element-Overlay.css">
    <link rel="stylesheet" href="assets/css/Popup-Element-Overlay.css">
    <link rel="stylesheet" href="assets/css/styles.css">
</head>

<body>
    <?php include ('../views/header.phtml');?>
    <nav class="navbar navbar-light navbar-expand-md">
        <div class="container">
            <a class="navbar-brand text-success" href="#">Booster by CA</a>
            <button class="navbar-toggler" data-toggle="collapse" data-target="#navcol-1">
                <span class="sr-only">Toggle navigation</span><span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse mr-auto"
                id="navcol-1">
                <ul class="nav navbar-nav"></ul>
                <p class="navbar-text links" style="margin-bottom:0px;">
                <a href="start.phtml">Accueil</a><strong>&nbsp;&gt;&nbsp;</strong>
                <a href="#">Navigation</a><strong>&nbsp;&nbsp;</strong></p>
                <a class="btn btn-primary ml-auto" role="button" href="../controllers/deconnexion.php" style="padding:6px 12px;margin-bottom:0px;background-color:#006a4e;margin-right:0px;">Se déconnecter</a>
            </div>
        </div>
    </nav>
    <div>
        <div class="container">
            <div class="row">
                <div class="col-md-4 col-xl-5 offset-md-1 offset-lg-1 offset-xl-0 cust_blogteaser">
                    <a href="dashboard.phtml"><img class="img-fluid" src="assets/img/desk.jpg"></a>
                    <h3>Analyser mon activité</h3>
                    <p class="text-secondary"><a href="#modalAct" data-toggle="modal">Plus d'informations</a></p>
                    <a href="#" class="h4"><i class="fa fa-arrow-circle-right"></i></a>
                </div>

                <div class="col-md-4 col-xl-5 offset-md-2 offset-lg-2 offset-xl-2 cust_blogteaser">
                    <a href="cartographie.phtml"><img class="img-fluid" src="assets/img/building.jpg"></a>
                    <h3>Localiser mes clients</h3>
                    <p class="text-secondary"><a href="#modalLocalCli" data-toggle="modal">Plus d'informations</a></p>
                    <a href="#" class="h4"><i class="fa fa-arrow-circle-right"></i></a>
                </div>

                <div class="col-md-4 col-xl-5 offset-md-1 offset-lg-1 offset-xl-0 cust_blogteaser">
                    <a href="profiling.phtml"><img class="img-fluid" src="assets/img/loft.jpg"></a>
                    <h3>Connaître mes clients</h3>
                    <p class="text-secondary"><a href="#modalKnowCli" data-toggle="modal">Plus d'informations</a></p>
                    <a href="#" class="h4"><i class="fa fa-arrow-circle-right"></i></a>
                </div>

                <div class="col-md-4 col-xl-5 offset-md-2 offset-lg-2 offset-xl-2 cust_blogteaser">
                    <a href="web-marketing.phtml"><img class="img-fluid" src="assets/img/minibus.jpeg"></a>
                    <h3>Evaluer ma présence sur le web</h3>
                    <p class="text-secondary"><a href="#modalWeb" data-toggle="modal">Plus d'informations</a></p>
                    <a href="#" class="h4"><i class="fa fa-arrow-circle-right"></i></a></div>
            </div>
        </div>
    </div>

    <div class="modal fade" role="dialog" tabindex="-1" id="modalAct">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h4 class="modal-title" style="color:rgb(0,0,0);">Analyser mon activité</h4>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">×</span>
                    </button>
                </div>
                <div class="modal-body">
                    <p style="color:#000000;">Contenu du modal</p>
                </div>
            </div>
        </div>
    </div>
    <div class="modal fade" role="dialog" tabindex="-1" id="modalLocalCli">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h4 class="modal-title">Localiser mes clients</h4>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">×</span>
                    </button>
                </div>

                <div class="modal-body">
                    <p>The content of your modal.</p>
                </div>
            </div>
        </div>
    </div>
    <div class="modal fade" role="dialog" tabindex="-1" id="modalKnowCli">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h4 class="modal-title">Connaître mes clients</h4>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">×</span>
                    </button>
                </div>
                <div class="modal-body">
                    <p>The content of your modal.</p>
                </div>
            </div>
        </div>
    </div>
    <div class="modal fade" role="dialog" tabindex="-1" id="modalWeb">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h4 class="modal-title">Evaluer ma présence sur le web</h4>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">×</span>
                    </button>
                </div>
                <div class="modal-body">
                    <p>The content of your modal.</p>
                </div>
            </div>
        </div>
    </div>
    <div class="footer-clean" style="padding-top:0px;">
        <footer>
            <div class="row">
                <div class="col-sm-6 col-md-4 footer-navigation">
                    <h3></h3>
                    <h2 style="color:#006a4e;padding-bottom:30px;">Credit Agricole</h2>
                    <p class="links"><a href="#">Acceuil</a><strong> · </strong>
                    <a href="#">Blog</a><strong>&nbsp;· </strong><a href="#">A Propos</a><strong> · </strong><a href="#">FAQ</a><strong> · </strong>
                    <a href="#">Contact</a></p>
                    <p class="company-name">Crédit Agricole Normandie © 2018</p>
                </div>
                <div class="col-sm-6 col-md-4 footer-contacts">
                    <div><span class="fa fa-map-marker footer-contacts-icon"> </span>
                        <p><span class="new-line-span">15 esplanade Brillaud de Laujardière<br></span> Caen, France</p>
                    </div>
                    <div><i class="fa fa-phone footer-contacts-icon"></i>
                        <p class="footer-center-info email text-left"><a href="tel:+33231552424">02 31 55 24 24</a><br></p>
                    </div>
                    <div><i class="fa fa-envelope footer-contacts-icon"></i>
                        <p> <a href="#" target="_blank">support@creditagricole.com</a></p>
                    </div>
                </div>
                <div class="clearfix"></div>
                <div class="col-md-4 footer-about">
                    <h4>A propos de l'entreprise</h4>
                    <p> Lorem ipsum dolor sit amet, consectateur adispicing elit. Fusce euismod convallis velit, eu auctor lacus vehicula sit amet. </p>
                    <div class="social-links social-icons"><a href="#"><i class="fa fa-facebook"></i></a>
                        <a href="#"><i class="fa fa-twitter"></i></a><a href="#"><i class="fa fa-linkedin"></i></a><a href="#"><i class="fa fa-github"></i></a>
                    </div>
                </div>
            </div>
        </footer>
    </div>
    <script src="assets/js/jquery.min.js"></script>
    <script src="assets/bootstrap/js/bootstrap.min.js"></script>
    <script src="assets/js/Popup-Element-Overlay.js"></script>
    <script src="assets/js/Subscribe-Popup-Window.js"></script>
</body>

</html>