<?php
require ('../controllers/verif_authentification.php');
?>
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Ping project</title>
    <link rel="stylesheet" href="assets/bootstrap/css/bootstrap.min.css">
    <link rel="stylesheet" href="assets/fonts/font-awesome.min.css">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Alegreya+Sans+SC">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Anton">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Archivo+Narrow">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Cookie">
    <link rel="stylesheet" href="assets/css/-Login-form-Page-BS4-.css">
    <link rel="stylesheet" href="assets/css/Article-Cards.css">
    <link rel="stylesheet" href="assets/css/Bold-BS4-Cards-with-Hover-Effect-115.css">
    <link rel="stylesheet" href="assets/css/Bold-BS4-Cards-with-Hover-Effect-115.css">
    <link rel="stylesheet" href="assets/css/Bold-BS4-Cards-with-Hover-Effect-50.css">
    <link rel="stylesheet" href="assets/css/Bold-BS4-Cards-with-Hover-Effect-50.css">
    <link rel="stylesheet" href="assets/css/Card-Group-Classic.css">
    <link rel="stylesheet" href="assets/css/Carousel-Hero.css">
    <link rel="stylesheet" href="assets/css/Footer-Clean.css">
    <link rel="stylesheet" href="assets/css/Google-Style-Login.css">
    <link rel="stylesheet" href="assets/css/Pretty-Footer.css">
    <link rel="stylesheet" href="assets/css/Highlight-Clean.css">
    <link rel="stylesheet" href="assets/css/News-Cards.css">
    <link rel="stylesheet" href="assets/css/Popup-Element-Overlay.css">
    <link rel="stylesheet" href="assets/css/Popup-Element-Overlay.css">
    <link rel="stylesheet" href="assets/css/styles.css">
</head>

<body>
    <?php include ('../views/header.phtml');?>
    <nav class="navbar navbar-light navbar-expand-md">
        <div class="container">
            <a class="navbar-brand text-success" href="#">Booster by CA</a>
            <button class="navbar-toggler" data-toggle="collapse" data-target="#navcol-1">
                <span class="sr-only">Toggle navigation</span><span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse mr-auto"id="navcol-1">
                <ul class="nav navbar-nav"></ul>
                <p class="navbar-text links" style="margin-bottom:0px;">
                <a href="start.phtml">Accueil</a><strong>&nbsp;&gt;&nbsp;</strong>
                <a href="start.phtml">Navigation</a><strong>&nbsp;&gt;&nbsp;</strong>
                <a href="#">Evaluer ma présence sur le web</a><strong>&nbsp;</strong></p>
                <a class="btn btn-primary ml-auto" role="button" href="../controllers/deconnexion.php" style="padding:6px 12px;margin-bottom:0px;background-color:#006a4e;margin-right:0px;">Se déconnecter</a></div>
        </div>
    </nav>
    <div class="highlight-clean">
        <div class="container">
            <div class="intro">
                <h2 class="text-center">Highlight</h2>
                <p class="text-center">Nunc luctus in metus eget fringilla. Aliquam sed justo ligula. Vestibulum nibh erat, pellentesque ut laoreet vitae. </p>
            </div>
            <div class="buttons"><a class="btn btn-primary" role="button" href="#">Primary</a><button class="btn btn-light" type="button">Secondary</button></div>
        </div>
    </div>
    <div class="footer-clean" style="padding-top:0px;">
        <footer>
            <div class="row">
                <div class="col-sm-6 col-md-4 footer-navigation">
                    <h3></h3>
                    <h2 style="color:#006a4e;padding-bottom:30px;">Credit Agricole</h2>
                    <p class="links"><a href="#">Acceuil</a><strong> · </strong><a href="#">Blog</a><strong>&nbsp;· </strong><a href="#">A Propos</a><strong> · </strong><a href="#">FAQ</a><strong> · </strong><a href="#">Contact</a></p>
                    <p class="company-name">Crédit Agricole Normandie © 2018</p>
                </div>
                <div class="col-sm-6 col-md-4 footer-contacts">
                    <div><span class="fa fa-map-marker footer-contacts-icon"> </span>
                        <p><span class="new-line-span">15 esplanade Brillaud de Laujardière<br></span> Caen, France</p>
                    </div>
                    <div><i class="fa fa-phone footer-contacts-icon"></i>
                        <p class="footer-center-info email text-left"><a href="tel:+33231552424">02 31 55 24 24</a><br></p>
                    </div>
                    <div><i class="fa fa-envelope footer-contacts-icon"></i>
                        <p> <a href="#" target="_blank">support@creditagricole.com</a></p>
                    </div>
                </div>
                <div class="clearfix"></div>
                <div class="col-md-4 footer-about">
                    <h4>A propos de l'entreprise</h4>
                    <p> Lorem ipsum dolor sit amet, consectateur adispicing elit. Fusce euismod convallis velit, eu auctor lacus vehicula sit amet. </p>
                    <div class="social-links social-icons"><a href="#"><i class="fa fa-facebook"></i></a><a href="#"><i class="fa fa-twitter"></i></a><a href="#"><i class="fa fa-linkedin"></i></a><a href="#"><i class="fa fa-github"></i></a></div>
                </div>
            </div>
        </footer>
    </div>
    <script src="assets/js/jquery.min.js"></script>
    <script src="assets/bootstrap/js/bootstrap.min.js"></script>
    <script src="assets/js/Popup-Element-Overlay.js"></script>
    <script src="assets/js/Subscribe-Popup-Window.js"></script>
</body>

</html>